Repository milieuinfo/webcomponent-vl-ui-pager, pull requests merged in 2020-03, with the labels that each got.

#20 E2E testen
  demo/vl-pager.html
  package.json
  test/e2e/components/vl-pager.js
  test/e2e/pager.test.js
  test/e2e/pages/vl-pager.page.js
Labels: chore

#22 E2E verbeteringen
  demo/vl-pager.html
  package-lock.json
  test/e2e/components/vl-pager.js
  test/e2e/pager.test.js
Labels: chore

#23 Change event gooien telkens de pagina van de pager verandert
  demo/vl-pager.html
  src/vl-pager.js
  test/e2e/components/vl-pager.js
  test/e2e/pager.test.js
  test/e2e/pages/vl-pager.page.js
  test/unit/vl-pager.test.html
Labels: enhancement

#24 Update vl-ui-util
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: chore, maintenance

#25 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore

#26 Update vl-ui-core
  package-lock.json
  package.json
Labels: chore
