Repository milieuinfo/webcomponent-vl-ui-pager, pull requests merged in 2020-06, with the labels that each got.

#37 Introductie vl-ui-demo en ESlint
  .eslintrc.json
  CODEOWNERS
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  demo/vl-pager.html
  index.js
  package-lock.json
  package.json
  src/index.js
  src/style.css
  src/style.css.map
  src/vl-pager.js
  test/e2e/components/vl-pager.js
  test/e2e/pager.test.js
  test/e2e/pages/vl-pager.page.js
  test/unit/vl-pager.test.html
Labels: chore

#38 Importeer sinon vanuit node_modules voor de unit testen
  demo/vl-pager.html
  package-lock.json
Labels: bugfix

#39 Update dependency @govflanders/vl-ui-core to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#42 Dependencies update
  package-lock.json
  package.json
  src/style.css
  test/e2e/pages/vl-pager.page.js
Labels: chore

#44 Deduplicatie NPM run scripts
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore
